spring:
  application:
    name: forum-demo
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: true
server:
  port: 8080
jwt:
  secret-key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000