create table topico
(
    id           bigint       not null generated by default as identity primary key,
    titulo       varchar(255) not null,
    mensagem     varchar(255) not null,
    autor_id     bigint       not null
        constraint topico_autor_fk references usuario,
    curso_id     bigint       not null
        constraint topico_curso_fk references curso,
    data_criacao timestamp(6) not null,
    status       varchar(255) not null
);