create table resposta
(
    id           bigint not null generated by default as identity primary key,
    mensagem     varchar(255) not null,
    solucao      boolean not null,
    data_criacao timestamp(6) not null,
    autor_id     bigint not null
        constraint resposta_autor_fk references usuario,
    topico_id    bigint not null
        constraint resposta_topico_fk references topico
);